input {
  http { port => 8080 }
  tcp { port => 5000 codec => json_lines }
}

filter {
  mutate { add_field => { "[@metadata][index]" => "interviewing-golang" } }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
